### ISSUE TITLE
$XLA_TARGET_PLATFORM gets read without hyphens

### ISSUE THREAD

**Issue by sylvesterroos** [elixir-nx/xla#104]
I'm trying to install Bumblebee in a non-standard environment (Elixir inside an Anaconda env) which requires me to set the XLA_TARGET_PLATFORM variable. This is because the platform gets read as `x86_64-conda-linux-gnu` and I need `x86_64-unknown-linux-gnu`.

The problem is that tokenizers seems to read/receive the wrong value. Here is the full error I get during compilation:
```
** (RuntimeError) expected XLA_TARGET_PLATFORM to be either ARCHITECTURE-OS-ABI or ARCHITECTURE-OS, got: x86_64unknownlinuxgnu
    (xla 0.8.0) lib/xla.ex:111: XLA.target_triplet/0
    (xla 0.8.0) lib/xla.ex:95: XLA.target/0
    (xla 0.8.0) lib/xla.ex:139: XLA.archive_path_for_precompiled_download/0
    (xla 0.8.0) lib/xla.ex:47: XLA.archive_path!/0
    /home2/minorai6/sylvester/transcription/deps/exla/mix.exs:113: EXLA.MixProject.extract_xla/1
    (mix 1.17.3) lib/mix/task.ex:574: Mix.Task.run_alias/6
    (mix 1.17.3) lib/mix/tasks/compile.all.ex:108: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.17.3) lib/mix/tasks/compile.all.ex:88: Mix.Tasks.Compile.All.compile/4
```

I'm setting the variable inside `config.exs`:
```
System.put_env("XLA_TARGET_PLATFORM", "x86_64-unknown-linux-gnu")
System.fetch_env!("XLA_TARGET_PLATFORM") |> dbg()
#=> "x86_64-unknown-linux-gnu"
```

**Comment by jonatanklosko** [comment]
Hey @sylvesterroos, the error is confusing because `other:` actually has the hyphens stripped. I will fix the error message.

What you actually want is this: `XLA_TARGET_PLATFORM=x86_64-linux-gnu`, so neither `conda` nor `unknown` is necessary.

**Comment by sylvesterroos** [comment]
EXLA seems to install correctly, but now I get the tokenizers error I remembered:
```
== Compilation error in file lib/tokenizers/native.ex ==
** (RuntimeError) precompiled NIF is not available for this target: "x86_64-conda-linux-gnu".
The available targets are:
 - aarch64-apple-darwin
 - aarch64-unknown-linux-gnu
 - aarch64-unknown-linux-musl
 - arm-unknown-linux-gnueabihf
 - riscv64gc-unknown-linux-gnu
 - x86_64-apple-darwin
 - x86_64-pc-windows-gnu
 - x86_64-pc-windows-msvc
 - x86_64-unknown-linux-gnu
 - x86_64-unknown-linux-musl
    lib/tokenizers/native.ex:8: (module)
```

This is with the following platform:
```
System.fetch_env!("XLA_TARGET_PLATFORM") #=> "x86_64-linux-gnu"
```

**Comment by jonatanklosko** [comment]
Ah, for tokenizers I think `TARGET_VENDOR=unknown` should do it.

**Comment by sylvesterroos** [comment]
That did the trick, thanks :)
