### ISSUE TITLE
$XLA_TARGET_PLATFORM gets read without hyphens

### ISSUE THREAD

**Issue by sylvesterroos** [elixir-nx/xla#105]
I'm trying to install Bumblebee in a non-standard environment (Elixir inside an Anaconda env) which requires me to set the XLA_TARGET_PLATFORM variable. This is because the platform gets read as x86_64-conda-linux-gnu and I need x86_64-unknown-linux-gnu.

The problem is that xla seems to read/receive the wrong value. Here is the full error I get during compilation:
```
** (RuntimeError) expected XLA_TARGET_PLATFORM to be either ARCHITECTURE-OS-ABI or ARCHITECTURE-OS, got: x86_64unknownlinuxgnu
    (xla 0.8.0) lib/xla.ex:111: XLA.target_triplet/0
    (xla 0.8.0) lib/xla.ex:95: XLA.target/0
    (xla 0.8.0) lib/xla.ex:139: XLA.archive_path_for_precompiled_download/0
    (xla 0.8.0) lib/xla.ex:47: XLA.archive_path!/0
    /home2/minorai6/sylvester/transcription/deps/exla/mix.exs:113: EXLA.MixProject.extract_xla/1
    (mix 1.17.3) lib/mix/task.ex:574: Mix.Task.run_alias/6
    (mix 1.17.3) lib/mix/tasks/compile.all.ex:108: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.17.3) lib/mix/tasks/compile.all.ex:88: Mix.Tasks.Compile.All.compile/4
```

I'm setting the variable inside config.exs:
```
System.put_env("XLA_TARGET_PLATFORM", "x86_64-unknown-linux-gnu")
System.fetch_env!("XLA_TARGET_PLATFORM") |> dbg()
#=> "x86_64-unknown-linux-gnu"
```

**Comment by jonatanklosko** [comment]
I transferred the issue to #104, so I will remove this as a duplicate :D
