### ISSUE TITLE
Can't download XLA archive. Certificate expired

### ISSUE THREAD

**Issue by mickel8** [elixir-nx/xla#41]
Hi,
when trying to install exla with Mix.install I am getting:

```
21:45:21.094 [info] Found a matching archive (xla_extension-x86_64-linux-gnu-cpu.tar.gz), going to download it
==> exla
could not compile dependency :exla, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile exla", update it with "mix deps.update exla" or clean it with "mix deps.clean exla"
** (RuntimeError) failed to download the XLA archive from https://github.com/elixir-nx/xla/releases/download/v0.4.4/xla_extension-x86_64-linux-gnu-cpu.tar.gz
    (xla 0.4.4) lib/xla.ex:203: XLA.download_archive!/2
    (xla 0.4.4) lib/xla.ex:33: XLA.archive_path!/0
    /home/michal/.cache/mix/installs/elixir-1.14.2-erts-13.1/e70174c9a0507b6eb7c9a038b5edd35d/deps/exla/mix.exs:112: EXLA.MixProject.extract_xla/1
    (mix 1.14.2) lib/mix/task.ex:492: Mix.Task.run_alias/6
    (mix 1.14.2) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.14.2) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
    (mix 1.14.2) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.14.2) lib/mix/tasks/compile.all.ex:33: Mix.Tasks.Compile.All.run/1
```

and from curl

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Looks like some certificate has expired on `Tue, 21 Mar 2023 23:59:59 GMT`

When trying to download tar with the source code manually (from the release section on github), it works correctly.

**Comment by josevalim** [comment]
We are just downloading it from GitHub though. Perhaps a temporary issue on GitHub side?

**Comment by josevalim** [comment]
Discussion here: https://news.ycombinator.com/item?id=35295216

**Comment by josevalim** [comment]
And it seems to be back up!

**Comment by mickel8** [comment]
Thanks! Works for me too
