### ISSUE TITLE
Precompiled binaries  for Alpine Linux

### ISSUE THREAD

**Issue by mickel8** [elixir-nx/xla#89]
Hi!
Are precompiled binaries for Alpine Linux planned? When I try to run xla on Alpine Linux 3.20.1 I am getting

```
==> xla
Compiling 2 files (.ex)
Generated xla app
could not compile dependency :exla, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile exla --force", update it with "mix deps.update exla" or clean it with "mix deps.clean exla"
==> exla
** (RuntimeError) none of the precompiled archives matches your target
  Expected:
    * xla_extension-x86_64-linux-musl-cpu.tar.gz
  Found:
    * xla_extension-aarch64-darwin-cpu.tar.gz
    * xla_extension-aarch64-linux-gnu-cpu.tar.gz
    * xla_extension-aarch64-linux-gnu-cuda118.tar.gz
    * xla_extension-aarch64-linux-gnu-cuda120.tar.gz
    * xla_extension-x86_64-darwin-cpu.tar.gz
    * xla_extension-x86_64-linux-gnu-cpu.tar.gz
    * xla_extension-x86_64-linux-gnu-cuda118.tar.gz
    * xla_extension-x86_64-linux-gnu-cuda120.tar.gz
    * xla_extension-x86_64-linux-gnu-tpu.tar.gz

You can compile XLA locally by setting an environment variable: XLA_BUILD=true
    (xla 0.5.1) lib/xla.ex:196: XLA.download_matching!/1
    (xla 0.5.1) lib/xla.ex:33: XLA.archive_path!/0
    /app/deps/exla/mix.exs:112: EXLA.MixProject.extract_xla/1
    (mix 1.17.2) lib/mix/task.ex:574: Mix.Task.run_alias/6
    (mix 1.17.2) lib/mix/tasks/compile.all.ex:108: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.17.2) lib/mix/tasks/compile.all.ex:88: Mix.Tasks.Compile.All.compile/4
    (mix 1.17.2) lib/mix/tasks/compile.all.ex:62: Mix.Tasks.Compile.All.run/1
    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
```

**Comment by seanmor5** [comment]
There are not. I've gone down the rabbit hole of precompiling XLA for Alpine previously and it's not great. At the time TensorFlow and LLVM required a bunch of manual patches to build properly on Alpine. It may have improved with the transition to OpenXLA. I can help provide guidance from the last time I did this if necessary

**Comment by mickel8** [comment]
Thanks, I see :thinking: 

Well, I am stuck as I need the newest ffmpeg (which ubuntu and debian do not provide) and XLA. That's why I thought about Alpine.

I will try to somehow get ffmpeg on debian from different repository or try to use fedora docker image.
